/**
 * HR Module with full feature permissions structure.
 * Use this to seed or update the HR module via PATCH /api/v1/modules/hr
 */

export const hrModuleFeatures = [
  {
    featureId: 1,
    featureKey: 'employeeManagement',
    featureName: 'Employee Management',
    featurePermissions: [
      { key: 'canViewEmployees', name: 'View Employees', permissionType: 'view' },
      { key: 'canCreateEmployee', name: 'Create Employee', permissionType: 'create' },
      { key: 'canUpdateEmployee', name: 'Update Employee', permissionType: 'update' },
      { key: 'canDeleteEmployee', name: 'Delete Employee', permissionType: 'delete' },
    ],
  },
  {
    featureId: 2,
    featureKey: 'payrollManagement',
    featureName: 'Payroll Management',
    featurePermissions: [
      { key: 'canViewPayroll', name: 'View Payroll', permissionType: 'view' },
      { key: 'canCreatePayroll', name: 'Create Payroll', permissionType: 'create' },
      { key: 'canUpdatePayroll', name: 'Update Payroll', permissionType: 'update' },
      { key: 'canDeletePayroll', name: 'Delete Payroll', permissionType: 'delete' },
    ],
  },
  {
    featureId: 3,
    featureKey: 'leaveManagement',
    featureName: 'Leave Management',
    featurePermissions: [
      { key: 'canViewLeaveHistory', name: 'View Leave History', permissionType: 'view' },
      { key: 'canCreateLeaveRequest', name: 'Create Leave Request', permissionType: 'create' },
      { key: 'canActionLeaveRequest', name: 'Action Leave Request', permissionType: 'update' },
      { key: 'canDeleteLeaveRequest', name: 'Delete Leave Request', permissionType: 'delete' },
    ],
  },
  {
    featureId: 4,
    featureKey: 'appraisalManagement',
    featureName: 'Appraisal Management',
    featurePermissions: [
      { key: 'canViewAppraisalHistory', name: 'View Appraisal History', permissionType: 'view' },
      { key: 'canCreateAppraisalPeriod', name: 'Create Appraisal Period', permissionType: 'create' },
      { key: 'canUpdateAppraisalPeriod', name: 'Update Appraisal Period', permissionType: 'update' },
      { key: 'canDeleteAppraisalPeriod', name: 'Delete Appraisal Period', permissionType: 'delete' },
      { key: 'canCreateKpi', name: 'Create Kpi', permissionType: 'create' },
      { key: 'canUpdateKpi', name: 'Update Kpi', permissionType: 'update' },
      { key: 'canDeleteKpi', name: 'Delete Kpi', permissionType: 'delete' },
      { key: 'canViewKpi', name: 'View Kpi', permissionType: 'view' },
      { key: 'canViewKpiRating', name: 'View Kpi Rating', permissionType: 'view' },
      { key: 'canCreateKpiRating', name: 'Create Kpi Rating', permissionType: 'create' },
      { key: 'canUpdateKpiRating', name: 'Update Kpi Rating', permissionType: 'update' },
      { key: 'canDeleteKpiRating', name: 'Delete Kpi Rating', permissionType: 'delete' },
      { key: 'canActionAppraisalRequest', name: 'Action Appraisal Request', permissionType: 'update' },
    ],
  },
  {
    featureId: 5,
    featureKey: 'expenseManagement',
    featureName: 'Expense Management',
    featurePermissions: [
      { key: 'canViewExpenseHistory', name: 'View Expense History', permissionType: 'view' },
      { key: 'canCreateExpenseRequest', name: 'Create Expense Request', permissionType: 'create' },
      { key: 'canActionExpenseRequest', name: 'Action Expense Request', permissionType: 'update' },
      { key: 'canDeleteExpenseRequest', name: 'Delete Expense Request', permissionType: 'delete' },
    ],
  },
  {
    featureId: 6,
    featureKey: 'calendarManagement',
    featureName: 'Calendar Management',
    featurePermissions: [
      { key: 'canViewCalender', name: 'View Calendar', permissionType: 'view' },
    ],
  },
  {
    featureId: 7,
    featureKey: 'settingsManagement',
    featureName: 'Settings Management',
    featurePermissions: [
      { key: 'canCreateDepartment', name: 'Create Department', permissionType: 'create' },
      { key: 'canViewDepartment', name: 'View Department', permissionType: 'view' },
      { key: 'canUpdateDepartment', name: 'Update Department', permissionType: 'update' },
      { key: 'canDeleteDepartment', name: 'Delete Department', permissionType: 'delete' },
      { key: 'canViewDesignation', name: 'View Designation', permissionType: 'view' },
      { key: 'canCreateDesignation', name: 'Create Designation', permissionType: 'create' },
      { key: 'canUpdateDesignation', name: 'Update Designation', permissionType: 'update' },
      { key: 'canDeleteDesignation', name: 'Delete Designation', permissionType: 'delete' },
      { key: 'canViewLeaveType', name: 'View Leave Type', permissionType: 'view' },
      { key: 'canCreateLeaveType', name: 'Create Leave Type', permissionType: 'create' },
      { key: 'canUpdateLeaveType', name: 'Update Leave Type', permissionType: 'update' },
      { key: 'canDeleteLeaveType', name: 'Delete Leave Type', permissionType: 'delete' },
      { key: 'canViewHoliday', name: 'View Holiday', permissionType: 'view' },
      { key: 'canCreateHoliday', name: 'Create Holiday', permissionType: 'create' },
      { key: 'canUpdateHoliday', name: 'Update Holiday', permissionType: 'update' },
      { key: 'canDeleteHoliday', name: 'Delete Holiday', permissionType: 'delete' },
      { key: 'canViewExpenseType', name: 'View Expense Type', permissionType: 'view' },
      { key: 'canCreateExpenseType', name: 'Create Expense Type', permissionType: 'create' },
      { key: 'canUpdateExpenseType', name: 'Update Expense Type', permissionType: 'update' },
      { key: 'canDeleteExpenseType', name: 'Delete Expense Type', permissionType: 'delete' },
      { key: 'canViewPayrollCredit', name: 'View Payroll Credit', permissionType: 'view' },
      { key: 'canCreatePayrollCredit', name: 'Create Payroll Credit', permissionType: 'create' },
      { key: 'canUpdatePayrollCredit', name: 'Update Payroll Credit', permissionType: 'update' },
      { key: 'canDeletePayrollCredit', name: 'Delete Payroll Credit', permissionType: 'delete' },
      { key: 'canViewPayrollDebit', name: 'View Payroll Debit', permissionType: 'view' },
      { key: 'canCreatePayrollDebit', name: 'Create Payroll Debit', permissionType: 'create' },
      { key: 'canUpdatePayrollDebit', name: 'Update Payroll Debit', permissionType: 'update' },
      { key: 'canDeletePayrollDebit', name: 'Delete Payroll Debit', permissionType: 'delete' },
    ],
  },
  {
    featureId: 8,
    featureKey: 'recruitmentManagement',
    featureName: 'Recruitment Management',
    featurePermissions: [
      { key: 'canViewJobListings', name: 'View Job Listings', permissionType: 'view' },
      { key: 'canCreateJobListing', name: 'Create Job Listing', permissionType: 'create' },
      { key: 'canUpdateJobListing', name: 'Update Job Listing', permissionType: 'update' },
      { key: 'canDeleteJobListing', name: 'Delete Job Listing', permissionType: 'delete' },
      { key: 'canViewApplications', name: 'View Applications', permissionType: 'view' },
      { key: 'canActionApplication', name: 'Action Application', permissionType: 'update' },
      { key: 'canCreateOfferLetter', name: 'Create Offer Letter', permissionType: 'create' },
    ],
  },
];
